"""Canonical FRED series specifications used by the foundation."""

from datetime import timedelta
from types import MappingProxyType

from data import (
    DataFrequency,
    SeriesSpecification,
    Transformation,
)


FRED_SERIES = MappingProxyType(
    {
        "unemployment": SeriesSpecification(
            provider_series_identifier="UNRATE",
            indicator="unemployment",
            category="labor",
            unit="percent",
            frequency=DataFrequency.MONTHLY,
            stale_after=timedelta(days=45),
            importance=1.0,
        ),
        "consumer_price_index": SeriesSpecification(
            provider_series_identifier="CPIAUCSL",
            indicator="consumer_price_index",
            category="inflation",
            unit="index",
            frequency=DataFrequency.MONTHLY,
            transformation=Transformation.LEVEL,
            stale_after=timedelta(days=45),
            importance=1.0,
        ),
        "industrial_production": SeriesSpecification(
            provider_series_identifier="INDPRO",
            indicator="industrial_production",
            category="growth",
            unit="index",
            frequency=DataFrequency.MONTHLY,
            transformation=Transformation.LEVEL,
            stale_after=timedelta(days=45),
            importance=1.0,
        ),
        "real_gdp": SeriesSpecification(
            provider_series_identifier="GDPC1",
            indicator="real_gross_domestic_product",
            category="growth",
            unit="billions_of_chained_2017_dollars",
            frequency=DataFrequency.QUARTERLY,
            transformation=Transformation.LEVEL,
            stale_after=timedelta(days=120),
            importance=1.0,
        ),
        "real_personal_consumption": SeriesSpecification(
            provider_series_identifier="PCEC96",
            indicator="real_personal_consumption_expenditures",
            category="consumption",
            unit="billions_of_chained_2017_dollars",
            frequency=DataFrequency.MONTHLY,
            transformation=Transformation.LEVEL,
            stale_after=timedelta(days=45),
            importance=0.9,
        ),
        "nonfarm_payrolls": SeriesSpecification(
            provider_series_identifier="PAYEMS",
            indicator="total_nonfarm_payroll_employment",
            category="labor",
            unit="thousands_of_persons",
            frequency=DataFrequency.MONTHLY,
            transformation=Transformation.LEVEL,
            stale_after=timedelta(days=45),
            importance=1.0,
        ),
        "initial_jobless_claims": SeriesSpecification(
            provider_series_identifier="ICSA",
            indicator="initial_unemployment_insurance_claims",
            category="labor",
            unit="persons",
            frequency=DataFrequency.WEEKLY,
            transformation=Transformation.LEVEL,
            stale_after=timedelta(days=14),
            importance=0.9,
        ),
        "housing_permits": SeriesSpecification(
            provider_series_identifier="PERMIT",
            indicator="new_private_housing_units_authorized",
            category="housing",
            unit="thousands_of_units",
            frequency=DataFrequency.MONTHLY,
            transformation=Transformation.LEVEL,
            stale_after=timedelta(days=45),
            importance=0.8,
        ),
        "ten_year_treasury": SeriesSpecification(
            provider_series_identifier="DGS10",
            indicator="ten_year_treasury_yield",
            category="rates",
            unit="percent",
            frequency=DataFrequency.DAILY,
            stale_after=timedelta(days=5),
            importance=0.9,
        ),
        "two_year_treasury": SeriesSpecification(
            provider_series_identifier="DGS2",
            indicator="two_year_treasury_yield",
            category="rates",
            unit="percent",
            frequency=DataFrequency.DAILY,
            stale_after=timedelta(days=5),
            importance=0.9,
        ),
        "federal_funds_rate": SeriesSpecification(
            provider_series_identifier="FEDFUNDS",
            indicator="federal_funds_rate",
            category="policy",
            unit="percent",
            frequency=DataFrequency.MONTHLY,
            stale_after=timedelta(days=45),
            importance=1.0,
        ),
        "federal_reserve_total_assets": SeriesSpecification(
            provider_series_identifier="WALCL",
            indicator="federal_reserve_total_assets",
            category="liquidity",
            unit="millions_of_us_dollars",
            frequency=DataFrequency.WEEKLY,
            transformation=Transformation.LEVEL,
            stale_after=timedelta(days=14),
            importance=0.9,
        ),
        "reserve_balances": SeriesSpecification(
            provider_series_identifier="WRESBAL",
            indicator="reserve_balances_with_federal_reserve_banks",
            category="liquidity",
            unit="millions_of_us_dollars",
            frequency=DataFrequency.WEEKLY,
            transformation=Transformation.LEVEL,
            stale_after=timedelta(days=14),
            importance=1.0,
        ),
        "treasury_general_account": SeriesSpecification(
            provider_series_identifier="WTREGEN",
            indicator="treasury_general_account",
            category="liquidity",
            unit="millions_of_us_dollars",
            frequency=DataFrequency.WEEKLY,
            transformation=Transformation.LEVEL,
            stale_after=timedelta(days=14),
            importance=0.9,
        ),
        "overnight_reverse_repo": SeriesSpecification(
            provider_series_identifier="RRPONTSYD",
            indicator="overnight_reverse_repurchase_agreements",
            category="liquidity",
            unit="billions_of_us_dollars",
            frequency=DataFrequency.DAILY,
            transformation=Transformation.LEVEL,
            stale_after=timedelta(days=5),
            importance=0.9,
        ),
        "broad_money_m2": SeriesSpecification(
            provider_series_identifier="M2SL",
            indicator="broad_money_m2",
            category="liquidity",
            unit="billions_of_us_dollars",
            frequency=DataFrequency.MONTHLY,
            transformation=Transformation.LEVEL,
            stale_after=timedelta(days=45),
            importance=0.9,
        ),
        "broad_dollar_index": SeriesSpecification(
            provider_series_identifier="DTWEXBGS",
            indicator="broad_us_dollar_index",
            category="funding",
            unit="index",
            frequency=DataFrequency.DAILY,
            transformation=Transformation.LEVEL,
            stale_after=timedelta(days=5),
            importance=0.8,
        ),
        "national_financial_conditions": SeriesSpecification(
            provider_series_identifier="NFCI",
            indicator="national_financial_conditions_index",
            category="financial_conditions",
            unit="index",
            frequency=DataFrequency.WEEKLY,
            transformation=Transformation.LEVEL,
            stale_after=timedelta(days=14),
            importance=1.0,
        ),
        "financial_stress_index": SeriesSpecification(
            provider_series_identifier="STLFSI4",
            indicator="financial_stress_index",
            category="financial_stress",
            unit="index",
            frequency=DataFrequency.WEEKLY,
            transformation=Transformation.LEVEL,
            stale_after=timedelta(days=14),
            importance=1.0,
        ),
    }
)

__all__ = ["FRED_SERIES"]
