"""Part 3 of the versioned general event-market rule catalog."""
from intelligence.event_market_rule_builders import (
    EventMarketDomain, EventMarketState, TransmissionDirection, rule, tx,
)

RULES_PART_3 = (
    rule(
        'energy-demand-weakening',
        EventMarketDomain.MACRO_GROWTH,
        EventMarketState.DEMAND_WEAKENING,
        ('recession', 'weak demand', 'demand slowdown', 'growth fears', 'economic slowdown', 'consumption falls', 'demand weakens'),
        context=('oil', 'crude', 'brent', 'wti', 'petroleum', 'energy demand'),
        excluded=(),
        channels=('growth', 'demand', 'commodity'),
        priority=0.9,
        chain=('Expected economic activity and petroleum consumption weaken.', 'Expected crude demand falls relative to available supply.', 'Oil prices and producer cash-flow expectations decline while the same growth shock pressures equities and credit.'),
        transmissions=(
            tx('crude_oil', TransmissionDirection.NEGATIVE, 0.85, 'Lower expected petroleum consumption weakens crude prices.', 'short_to_medium_term'),
            tx('energy_producers', TransmissionDirection.NEGATIVE, 0.7, 'Lower expected crude realizations reduce producer cash flow.', 'short_to_medium_term'),
            tx('broad_equities', TransmissionDirection.NEGATIVE, 0.6, 'The oil decline reflects weaker growth rather than a favorable supply shock.', 'short_to_medium_term'),
            tx('credit', TransmissionDirection.NEGATIVE, 0.55, 'A weaker growth outlook raises cyclical credit risk.', 'short_to_medium_term'),
            tx('treasuries', TransmissionDirection.POSITIVE, 0.4, 'Weaker growth can reduce expected policy rates and increase defensive demand.', 'short_to_medium_term'),
        ),
        alternatives=('A supply increase or positioning unwind may also be lowering oil.', 'Policy easing may offset part of the growth shock.'),
    ),
    rule(
        'energy-demand-strengthening',
        EventMarketDomain.MACRO_GROWTH,
        EventMarketState.DEMAND_STRENGTHENING,
        ('strong demand', 'demand strengthens', 'demand accelerates', 'consumption rises', 'growth accelerates'),
        context=('oil', 'crude', 'brent', 'wti', 'petroleum', 'energy demand'),
        excluded=(),
        channels=('growth', 'demand', 'commodity'),
        priority=0.88,
        chain=('Expected economic activity and petroleum consumption strengthen.', 'Expected crude demand rises relative to available supply.', 'Oil prices and producer cash-flow expectations receive support, while input-intensive sectors may face higher costs.'),
        transmissions=(
            tx('crude_oil', TransmissionDirection.POSITIVE, 0.7, 'Higher expected petroleum consumption supports crude prices.', 'short_to_medium_term'),
            tx('energy_producers', TransmissionDirection.POSITIVE, 0.6, 'Higher expected crude realizations support producer cash flow.', 'short_to_medium_term'),
            tx('airlines', TransmissionDirection.NEGATIVE, 0.35, 'Higher fuel expectations can pressure margins.', 'short_to_medium_term'),
            tx('inflation_expectations', TransmissionDirection.POSITIVE, 0.3, 'Higher energy demand can increase price pressure.', 'short_to_medium_term'),
        ),
        alternatives=('Supply growth may absorb stronger demand.', 'The demand increase may be seasonal or already priced.'),
    ),
    rule(
        'commodity-supply-tightening',
        EventMarketDomain.COMMODITY_SUPPLY,
        EventMarketState.SUPPLY_TIGHTENING,
        ('production cut', 'output cut', 'supply disruption', 'pipeline outage', 'refinery outage', 'mine closure', 'export halt', 'inventory draw', 'crop failure', 'shipping disruption', 'port closure', 'capacity offline'),
        context=(),
        excluded=(),
        channels=('supply', 'commodity', 'climate_weather', 'operational'),
        priority=0.75,
        chain=('Available physical supply or transport capacity declines.', 'Scarcity and replacement costs rise.', 'Producers may benefit while consumers and inflation-sensitive assets face pressure.'),
        transmissions=(
            tx('affected_commodity', TransmissionDirection.POSITIVE, 0.8, 'Lower available supply raises scarcity value.', 'short_to_medium_term'),
            tx('commodity_producers', TransmissionDirection.POSITIVE, 0.6, 'Higher realized prices can support producer cash flow.', 'short_to_medium_term'),
            tx('commodity_consumers', TransmissionDirection.NEGATIVE, 0.6, 'Higher input costs pressure margins.', 'short_to_medium_term'),
            tx('inflation_expectations', TransmissionDirection.POSITIVE, 0.45, 'Higher input costs can lift near-term inflation.', 'short_to_medium_term'),
            tx('supply_chain', TransmissionDirection.NEGATIVE, 0.55, 'Reduced capacity raises delay and substitution costs.', 'short_to_medium_term'),
        ),
        alternatives=('Inventories, spare capacity, or demand weakness may offset the shortage.', 'The disruption may be local or temporary rather than system-wide.'),
    ),
    rule(
        'macro-growth-downside',
        EventMarketDomain.MACRO_GROWTH,
        EventMarketState.DEMAND_WEAKENING,
        ('gdp misses', 'growth misses', 'growth slows', 'recession', 'contraction', 'retail sales fall', 'industrial production falls', 'pmi contracts', 'new orders fall', 'consumer spending weakens', 'economic slowdown'),
        context=(),
        excluded=(),
        channels=('growth', 'demand', 'earnings', 'credit'),
        priority=0.75,
        chain=('Expected economic activity and revenue growth weaken.', 'Cyclical earnings, commodity demand, and credit capacity deteriorate.', 'Defensive assets may benefit from lower expected rates and risk aversion.'),
        transmissions=(
            tx('cyclical_equities', TransmissionDirection.NEGATIVE, 0.7, 'Lower expected activity pressures cyclical revenue and margins.', 'short_to_medium_term'),
            tx('broad_equities', TransmissionDirection.NEGATIVE, 0.55, 'Lower expected earnings pressure equities.', 'short_to_medium_term'),
            tx('credit', TransmissionDirection.NEGATIVE, 0.6, 'Weaker cash flows can widen spreads and raise default risk.', 'short_to_medium_term'),
            tx('affected_commodity', TransmissionDirection.NEGATIVE, 0.45, 'Lower expected activity reduces commodity demand.', 'short_to_medium_term'),
            tx('treasuries', TransmissionDirection.POSITIVE, 0.5, 'Lower growth can reduce expected policy rates and increase defensive demand.', 'short_to_medium_term'),
        ),
        alternatives=('Policy easing may offset the growth shock.', 'The data may be temporary, backward-looking, or distorted.'),
    ),
    rule(
        'labor-tightening',
        EventMarketDomain.LABOR,
        EventMarketState.LABOR_TIGHTENING,
        ('payrolls beat', 'jobs beat', 'unemployment falls', 'wage growth rises', 'job openings rise', 'labor market tightens', 'hiring accelerates'),
        context=(),
        excluded=(),
        channels=('growth', 'inflation', 'policy'),
        priority=0.75,
        chain=('Labor demand and household-income support strengthen.', 'Growth expectations improve, but wage and inflation pressure may rise.', 'The event can be positive for cyclicals and negative for rate-sensitive assets.'),
        transmissions=(
            tx('cyclical_equities', TransmissionDirection.POSITIVE, 0.45, 'Stronger employment supports consumption and revenue.', 'short_to_medium_term'),
            tx('policy_rate_expectations', TransmissionDirection.POSITIVE, 0.55, 'A tighter labor market can delay easing.', 'short_to_medium_term'),
            tx('bond_prices', TransmissionDirection.NEGATIVE, 0.5, 'Higher expected rates pressure bond prices.', 'short_to_medium_term'),
            tx('growth_equities', TransmissionDirection.NEGATIVE, 0.35, 'Higher discount rates can offset the growth benefit.', 'short_to_medium_term'),
        ),
        alternatives=('Productivity gains may absorb wage growth without inflation.', 'The report may be revised or concentrated in low-quality jobs.'),
    ),
    rule(
        'monetary-policy-tightening',
        EventMarketDomain.MONETARY_POLICY,
        EventMarketState.POLICY_TIGHTENING,
        ('rate hike', 'raises rates', 'hawkish', 'policy tightening', 'quantitative tightening', 'liquidity withdrawal', 'faster balance sheet runoff', 'higher for longer'),
        context=('central bank', 'federal reserve', 'fed', 'ecb', 'bank of england', 'boj', 'policy rate', 'fomc'),
        excluded=(),
        channels=('policy', 'liquidity', 'discount_rate'),
        priority=0.75,
        chain=('Expected policy rates or liquidity constraints increase.', 'Discount rates and financing pressure rise.', 'Long-duration assets, credit, and rate-sensitive sectors face pressure.'),
        transmissions=(
            tx('bond_prices', TransmissionDirection.NEGATIVE, 0.75, 'Higher expected rates pressure bond prices.', 'short_to_medium_term'),
            tx('growth_equities', TransmissionDirection.NEGATIVE, 0.6, 'Higher discount rates pressure long-duration valuations.', 'short_to_medium_term'),
            tx('credit', TransmissionDirection.NEGATIVE, 0.5, 'Tighter financing conditions pressure credit.', 'short_to_medium_term'),
            tx('real_estate', TransmissionDirection.NEGATIVE, 0.5, 'Higher financing costs pressure rate-sensitive assets.', 'short_to_medium_term'),
            tx('us_dollar', TransmissionDirection.POSITIVE, 0.35, 'Higher relative yields can support the currency.', 'short_to_medium_term'),
        ),
        alternatives=('Strong growth may offset part of the valuation pressure.', 'Markets may already have priced the policy path.'),
    ),
    rule(
        'trade-easing',
        EventMarketDomain.TRADE_SANCTIONS,
        EventMarketState.TRADE_EASING,
        ('tariffs removed', 'tariffs reduced', 'sanctions lifted', 'export controls eased', 'trade agreement', 'market access restored', 'embargo lifted', 'trade deal'),
        context=(),
        excluded=(),
        channels=('regulation', 'geopolitical', 'supply', 'currency'),
        priority=0.75,
        chain=('Cross-border access to goods, technology, capital, or payments improves.', 'Affected supply-chain costs and lost-demand risks decline.', 'Exporters, importers, and globally exposed sectors receive support.'),
        transmissions=(
            tx('affected_exporters', TransmissionDirection.POSITIVE, 0.6, 'Improved market access supports expected sales.', 'short_to_medium_term'),
            tx('affected_importers', TransmissionDirection.POSITIVE, 0.5, 'Lower trade friction reduces input costs.', 'short_to_medium_term'),
            tx('supply_chain', TransmissionDirection.POSITIVE, 0.55, 'Easier trade reduces sourcing and compliance friction.', 'short_to_medium_term'),
            tx('inflation_expectations', TransmissionDirection.NEGATIVE, 0.25, 'Lower landed costs can reduce price pressure.', 'short_to_medium_term'),
        ),
        alternatives=('The agreement may be narrow, delayed, or difficult to enforce.', 'Domestic substitutes may lose prior protection.'),
    ),
    rule(
        'corporate-negative',
        EventMarketDomain.CORPORATE,
        EventMarketState.CORPORATE_NEGATIVE,
        ('earnings miss', 'revenue miss', 'cuts guidance', 'guidance cut', 'profit warning', 'margin contracts', 'dividend cut', 'share offering', 'product recall', 'trial failure', 'approval denied', 'contract lost'),
        context=(),
        excluded=(),
        channels=('earnings', 'operational', 'credit'),
        priority=0.75,
        chain=('Expected issuer revenue, margin, capital structure, or strategic position deteriorates.', 'Issuer cash-flow and valuation assumptions decline.', 'Peers and suppliers move only when the event changes a broader industry assumption.'),
        transmissions=(
            tx('affected_issuer', TransmissionDirection.NEGATIVE, 0.8, 'The event weakens issuer-specific expected cash flow or raises risk.', 'short_to_medium_term'),
            tx('affected_sector', TransmissionDirection.NEGATIVE, 0.35, 'The event may provide an adverse peer read-through.', 'short_to_medium_term'),
            tx('issuer_credit', TransmissionDirection.NEGATIVE, 0.45, 'Weaker cash flow or higher leverage can pressure credit quality.', 'short_to_medium_term'),
        ),
        alternatives=('The weakness may be temporary, conservative guidance, or already priced.', 'Competitors may benefit from the issuer-specific setback.'),
    ),
    rule(
        'regulatory-tightening',
        EventMarketDomain.REGULATION_LEGAL,
        EventMarketState.REGULATORY_TIGHTENING,
        ('final rule', 'new regulation', 'regulatory crackdown', 'antitrust lawsuit', 'license revoked', 'permit denied', 'enforcement action', 'fine imposed', 'investigation opened', 'ban announced', 'capital requirement increased'),
        context=(),
        excluded=(),
        channels=('regulation', 'operational', 'earnings'),
        priority=0.75,
        chain=('Compliance costs, operating restrictions, or legal-loss probability rise.', 'Affected issuer or sector cash-flow expectations decline.', 'Competitors may benefit only when the action changes relative industry structure.'),
        transmissions=(
            tx('affected_issuer', TransmissionDirection.NEGATIVE, 0.7, 'Higher costs or restrictions reduce issuer value.', 'short_to_medium_term'),
            tx('affected_sector', TransmissionDirection.NEGATIVE, 0.5, 'The rule can reduce sector profitability or flexibility.', 'short_to_medium_term'),
            tx('compliance_beneficiaries', TransmissionDirection.POSITIVE, 0.25, 'Demand for compliance or substitute services may rise.', 'short_to_medium_term'),
        ),
        alternatives=('Implementation may be delayed, narrowed, or successfully challenged.', 'Well-capitalized incumbents may gain share despite higher compliance costs.'),
    ),
    rule(
        'operational-restoration',
        EventMarketDomain.OPERATIONAL_CYBER,
        EventMarketState.OPERATIONAL_RESTORATION,
        ('service restored', 'systems restored', 'operations resume', 'production resumes', 'network recovered', 'outage resolved', 'cyber incident contained', 'factory reopens', 'normal operations restored'),
        context=(),
        excluded=(),
        channels=('cyber', 'operational', 'earnings'),
        priority=0.75,
        chain=('Operational capacity or customer access returns.', 'Expected lost revenue and remediation uncertainty decline.', 'Affected issuers and dependencies reprice toward normal operations.'),
        transmissions=(
            tx('affected_issuer', TransmissionDirection.POSITIVE, 0.6, 'Restored operations reduce expected loss and uncertainty.', 'short_to_medium_term'),
            tx('affected_customers', TransmissionDirection.POSITIVE, 0.35, 'Service restoration reduces downtime and switching costs.', 'short_to_medium_term'),
            tx('volatility', TransmissionDirection.NEGATIVE, 0.25, 'Reduced uncertainty lowers risk premiums.', 'short_to_medium_term'),
        ),
        alternatives=('Hidden damage, legal exposure, or customer loss may persist after restoration.', 'The recovery may be temporary or capacity-constrained.'),
    ),
    rule(
        'public-health-escalation',
        EventMarketDomain.PUBLIC_HEALTH,
        EventMarketState.HEALTH_ESCALATION,
        ('outbreak', 'epidemic', 'pandemic', 'new variant', 'cases surge', 'public health emergency', 'travel restrictions', 'hospitalizations rise'),
        context=(),
        excluded=(),
        channels=('growth', 'operational', 'public_health', 'demand'),
        priority=0.75,
        chain=('Health risk and behavioral restrictions increase.', 'Travel, labor supply, consumer activity, and healthcare demand shift.', 'Affected sectors reprice according to severity, geography, and policy response.'),
        transmissions=(
            tx('travel_leisure', TransmissionDirection.NEGATIVE, 0.6, 'Travel and gathering activity may decline.', 'short_to_medium_term'),
            tx('healthcare_demand', TransmissionDirection.POSITIVE, 0.45, 'Testing, treatment, and protective demand can rise.', 'short_to_medium_term'),
            tx('broad_equities', TransmissionDirection.NEGATIVE, 0.35, 'Growth and operational uncertainty can pressure risk assets.', 'short_to_medium_term'),
            tx('volatility', TransmissionDirection.POSITIVE, 0.4, 'Uncertain transmission and policy response increase risk premiums.', 'short_to_medium_term'),
        ),
        alternatives=('The event may remain geographically contained or clinically mild.', 'Vaccines, treatments, or behavior changes may limit economic disruption.'),
    ),
    rule(
        'political-resolution',
        EventMarketDomain.POLITICAL_ELECTION,
        EventMarketState.POLITICAL_RESOLUTION,
        ('election result confirmed', 'peaceful transfer', 'coalition formed', 'government formed', 'budget passed', 'shutdown ended', 'debt ceiling agreement'),
        context=(),
        excluded=(),
        channels=('policy', 'currency', 'volatility'),
        priority=0.75,
        chain=('The near-term authority and policy path become clearer.', 'Country, currency, and volatility risk premiums decline.', 'Sector effects then depend on the confirmed policy program.'),
        transmissions=(
            tx('affected_region', TransmissionDirection.POSITIVE, 0.45, 'Reduced institutional uncertainty lowers required returns.', 'short_to_medium_term'),
            tx('local_currency', TransmissionDirection.POSITIVE, 0.35, 'Lower uncertainty can reduce capital-flight pressure.', 'short_to_medium_term'),
            tx('volatility', TransmissionDirection.NEGATIVE, 0.4, 'A clearer policy path reduces risk premiums.', 'short_to_medium_term'),
        ),
        alternatives=('The confirmed policy program may still be adverse for some sectors.', 'Implementation disputes may restore uncertainty.'),
    ),
    rule(
        'currency-depreciation',
        EventMarketDomain.CURRENCY,
        EventMarketState.CURRENCY_DEPRECIATION,
        ('currency devalues', 'currency falls', 'currency weakens', 'devaluation', 'intervention fails', 'capital controls', 'fx reserves fall'),
        context=(),
        excluded=(),
        channels=('currency', 'inflation', 'credit'),
        priority=0.75,
        chain=('The local currency loses purchasing power relative to external currencies.', 'Imported inflation and foreign-currency debt burdens rise.', 'Exporters may benefit while importers, consumers, and local credit face pressure.'),
        transmissions=(
            tx('local_currency', TransmissionDirection.NEGATIVE, 0.8, 'Depreciation reflects lower relative demand for the currency.', 'short_to_medium_term'),
            tx('local_exporters', TransmissionDirection.POSITIVE, 0.4, 'Foreign revenue translates into more local currency.', 'short_to_medium_term'),
            tx('local_importers', TransmissionDirection.NEGATIVE, 0.55, 'Imported inputs become more expensive.', 'short_to_medium_term'),
            tx('local_inflation', TransmissionDirection.POSITIVE, 0.5, 'Imported prices rise.', 'short_to_medium_term'),
            tx('foreign_currency_debt', TransmissionDirection.NEGATIVE, 0.55, 'Debt service becomes more expensive in local currency.', 'short_to_medium_term'),
        ),
        alternatives=('Export gains may offset some domestic pressure.', 'Credible intervention or policy tightening may stabilize the currency.'),
    ),
)

__all__=["RULES_PART_3"]
