"""Part 1 of the versioned general event-market rule catalog."""
from intelligence.event_market_rule_builders import (
    EventMarketDomain, EventMarketState, TransmissionDirection, rule, tx,
)

RULES_PART_1 = (
    rule(
        'energy-geopolitical-deescalation',
        EventMarketDomain.COMMODITY_SUPPLY,
        EventMarketState.GEOPOLITICAL_DEESCALATION,
        ('ceasefire', 'truce', 'peace deal', 'peace agreement', 'halt strikes', 'paused strikes', 'de-escalation', 'deescalation', 'talks progress', 'negotiations advance', 'shipping resumes', 'strait reopens'),
        context=('oil', 'crude', 'brent', 'wti', 'tanker', 'hormuz', 'persian gulf', 'energy shipping', 'petroleum'),
        excluded=(),
        channels=('geopolitical', 'supply', 'commodity'),
        priority=0.92,
        chain=('The probability of conflict-related energy disruption declines.', 'Expected tanker, pipeline, or export impairment falls.', 'The geopolitical supply-risk premium embedded in crude prices contracts.', 'Lower fuel and input-cost expectations can reduce inflation pressure and support oil-consuming sectors.'),
        transmissions=(
            tx('crude_oil', TransmissionDirection.NEGATIVE, 0.9, "Lower disruption probability removes part of crude oil's supply-risk premium.", 'immediate'),
            tx('energy_producers', TransmissionDirection.NEGATIVE, 0.65, 'Lower expected crude realizations reduce producer pricing support.', 'short_to_medium_term'),
            tx('airlines', TransmissionDirection.POSITIVE, 0.65, 'Lower jet-fuel expectations can improve margins.', 'short_to_medium_term'),
            tx('transportation', TransmissionDirection.POSITIVE, 0.55, 'Lower fuel and freight-risk costs can improve margins.', 'short_to_medium_term'),
            tx('inflation_expectations', TransmissionDirection.NEGATIVE, 0.45, 'Lower energy prices reduce near-term inflation pressure.', 'short_to_medium_term'),
        ),
        alternatives=('Physical shipping may remain impaired despite political statements.', 'Oil may instead be moving because of demand, inventories, or producer policy.'),
    ),
    rule(
        'geopolitical-escalation',
        EventMarketDomain.GEOPOLITICS,
        EventMarketState.GEOPOLITICAL_ESCALATION,
        ('military strike', 'airstrike', 'missile strike', 'invasion', 'blockade', 'retaliation', 'war expands', 'armed conflict', 'mobilization', 'state of emergency', 'shipping attacked', 'border clashes'),
        context=(),
        excluded=(),
        channels=('geopolitical', 'supply', 'volatility'),
        priority=0.75,
        chain=('The probability of conflict, sanctions, or physical disruption rises.', 'Supply, currency, and tail-risk premiums increase.', 'Affected regions and broad risk assets reprice for higher uncertainty and costs.'),
        transmissions=(
            tx('geopolitical_risk', TransmissionDirection.POSITIVE, 0.9, 'Escalation increases the geopolitical risk premium.', 'immediate'),
            tx('volatility', TransmissionDirection.POSITIVE, 0.75, 'Uncertainty increases demand for protection.', 'immediate'),
            tx('broad_equities', TransmissionDirection.NEGATIVE, 0.55, 'Higher uncertainty and input-cost risk pressure risk assets.', 'short_to_medium_term'),
            tx('defense', TransmissionDirection.POSITIVE, 0.45, 'Expected security spending can rise.', 'short_to_medium_term'),
            tx('affected_region', TransmissionDirection.NEGATIVE, 0.75, 'Regional assets face higher disruption, capital-flight, and risk-premium pressure.', 'short_to_medium_term'),
        ),
        alternatives=('The conflict may remain contained and leave economic flows intact.', 'Diplomatic intervention or spare capacity may reverse the initial reaction.'),
    ),
    rule(
        'macro-growth-upside',
        EventMarketDomain.MACRO_GROWTH,
        EventMarketState.DEMAND_STRENGTHENING,
        ('gdp beats', 'growth beats', 'growth accelerates', 'retail sales beat', 'industrial production rises', 'pmi expands', 'new orders rise', 'consumer spending rises', 'economic activity strengthens', 'soft landing'),
        context=(),
        excluded=(),
        channels=('growth', 'demand', 'earnings'),
        priority=0.75,
        chain=('Expected economic activity and revenue growth improve.', 'Cyclical earnings and credit capacity strengthen.', 'Rates may rise if stronger demand also raises inflation or delays easing.'),
        transmissions=(
            tx('cyclical_equities', TransmissionDirection.POSITIVE, 0.65, 'Higher expected activity supports cyclical revenue and margins.', 'short_to_medium_term'),
            tx('broad_equities', TransmissionDirection.POSITIVE, 0.5, 'Higher expected earnings support equities.', 'short_to_medium_term'),
            tx('credit', TransmissionDirection.POSITIVE, 0.5, 'Stronger cash flows can improve credit quality.', 'short_to_medium_term'),
            tx('industrial_metals', TransmissionDirection.POSITIVE, 0.4, 'Stronger activity can increase physical demand.', 'short_to_medium_term'),
            tx('bond_prices', TransmissionDirection.NEGATIVE, 0.35, 'Stronger growth can lift expected policy rates and yields.', 'short_to_medium_term'),
        ),
        alternatives=('The upside may already be priced or may be revised away.', 'Inflation and policy tightening may outweigh the earnings benefit.'),
    ),
    rule(
        'inflation-downside',
        EventMarketDomain.INFLATION,
        EventMarketState.INFLATION_DECELERATION,
        ('cpi misses', 'inflation misses', 'inflation falls', 'inflation slows', 'inflation cools', 'disinflation', 'ppi misses', 'core inflation falls', 'price pressures ease', 'inflation expectations fall'),
        context=(),
        excluded=(),
        channels=('inflation', 'discount_rate', 'policy'),
        priority=0.75,
        chain=('Expected inflation falls relative to prior expectations.', 'Expected policy rates and nominal yields decline.', 'Long-duration assets and rate-sensitive sectors receive valuation support.'),
        transmissions=(
            tx('inflation_expectations', TransmissionDirection.NEGATIVE, 0.8, 'The release lowers expected inflation.', 'short_to_medium_term'),
            tx('policy_rate_expectations', TransmissionDirection.NEGATIVE, 0.65, 'Lower inflation can permit easier policy.', 'short_to_medium_term'),
            tx('bond_prices', TransmissionDirection.POSITIVE, 0.65, 'Lower expected yields support bond prices.', 'short_to_medium_term'),
            tx('growth_equities', TransmissionDirection.POSITIVE, 0.55, 'Lower discount rates support long-duration valuations.', 'short_to_medium_term'),
            tx('real_estate', TransmissionDirection.POSITIVE, 0.45, 'Lower financing-rate expectations support rate-sensitive assets.', 'short_to_medium_term'),
        ),
        alternatives=('Disinflation may reflect weak demand rather than a benign supply improvement.', 'The release may not be sufficient to change policy expectations.'),
    ),
    rule(
        'monetary-policy-easing',
        EventMarketDomain.MONETARY_POLICY,
        EventMarketState.POLICY_EASING,
        ('rate cut', 'cuts rates', 'dovish', 'policy easing', 'quantitative easing', 'liquidity injection', 'ends tightening', 'slower balance sheet runoff'),
        context=('central bank', 'federal reserve', 'fed', 'ecb', 'bank of england', 'boj', 'policy rate', 'fomc'),
        excluded=(),
        channels=('policy', 'liquidity', 'discount_rate'),
        priority=0.75,
        chain=('Expected policy rates or liquidity constraints decline.', 'Discount rates and financing pressure ease.', 'Risk assets and bond prices receive support unless easing signals severe growth stress.'),
        transmissions=(
            tx('bond_prices', TransmissionDirection.POSITIVE, 0.75, 'Lower expected rates support bond prices.', 'short_to_medium_term'),
            tx('growth_equities', TransmissionDirection.POSITIVE, 0.6, 'Lower discount rates support long-duration valuations.', 'short_to_medium_term'),
            tx('credit', TransmissionDirection.POSITIVE, 0.5, 'Easier financing conditions can support credit.', 'short_to_medium_term'),
            tx('real_estate', TransmissionDirection.POSITIVE, 0.5, 'Lower financing costs support rate-sensitive assets.', 'short_to_medium_term'),
            tx('us_dollar', TransmissionDirection.NEGATIVE, 0.35, 'Lower relative yields can pressure the currency.', 'short_to_medium_term'),
        ),
        alternatives=('Easing may be a response to severe growth or financial stress.', 'Markets may have priced the action before the announcement.'),
    ),
    rule(
        'fiscal-contraction',
        EventMarketDomain.FISCAL_POLICY,
        EventMarketState.FISCAL_CONTRACTION,
        ('austerity', 'spending cuts', 'tax increase', 'fiscal contraction', 'budget cuts', 'government shutdown', 'debt ceiling impasse'),
        context=(),
        excluded=(),
        channels=('growth', 'credit', 'policy'),
        priority=0.75,
        chain=('Expected public spending or disposable income declines.', 'Near-term growth and beneficiary-sector demand weaken.', 'Lower inflation pressure may support bonds, while policy dysfunction can raise risk premiums.'),
        transmissions=(
            tx('cyclical_equities', TransmissionDirection.NEGATIVE, 0.5, 'Lower fiscal demand pressures activity and revenue.', 'short_to_medium_term'),
            tx('government_contractors', TransmissionDirection.NEGATIVE, 0.55, 'Budget reductions can reduce awarded demand.', 'short_to_medium_term'),
            tx('bond_prices', TransmissionDirection.POSITIVE, 0.3, 'Lower growth and inflation can support bonds.', 'short_to_medium_term'),
            tx('volatility', TransmissionDirection.POSITIVE, 0.35, 'Fiscal or debt-ceiling dysfunction can raise uncertainty.', 'short_to_medium_term'),
        ),
        alternatives=('Credibility gains may reduce long-term risk premiums.', 'Private demand or monetary easing may offset the contraction.'),
    ),
    rule(
        'corporate-positive',
        EventMarketDomain.CORPORATE,
        EventMarketState.CORPORATE_POSITIVE,
        ('earnings beat', 'revenue beat', 'raises guidance', 'guidance raised', 'profit rises', 'margin expands', 'dividend increase', 'buyback announced', 'contract award', 'major order', 'approval granted', 'drug approved'),
        context=(),
        excluded=(),
        channels=('earnings', 'operational', 'sentiment'),
        priority=0.75,
        chain=('Expected issuer revenue, margin, capital return, or strategic position improves.', 'Issuer cash-flow and valuation assumptions rise.', 'Peers and suppliers move only when the event changes a broader industry assumption.'),
        transmissions=(
            tx('affected_issuer', TransmissionDirection.POSITIVE, 0.8, 'The event improves issuer-specific expected cash flow or risk.', 'short_to_medium_term'),
            tx('affected_sector', TransmissionDirection.POSITIVE, 0.35, 'The event may provide a favorable peer read-through.', 'short_to_medium_term'),
            tx('issuer_credit', TransmissionDirection.POSITIVE, 0.35, 'Improved cash flow can support credit quality.', 'short_to_medium_term'),
        ),
        alternatives=('The positive result may be one-time, priced in, or lower quality than the headline suggests.', 'Industry read-through may be weak or negative for competitors.'),
    ),
    rule(
        'credit-relief',
        EventMarketDomain.CREDIT_FINANCIAL_STABILITY,
        EventMarketState.CREDIT_RELIEF,
        ('capital raise completed', 'liquidity restored', 'deposit outflows stabilize', 'rescue package', 'guarantee announced', 'credit upgrade', 'debt repaid', 'restructuring agreement', 'funding secured', 'bank acquired'),
        context=(),
        excluded=(),
        channels=('credit', 'liquidity', 'counterparty'),
        priority=0.75,
        chain=('The probability of loss, funding stress, or counterparty impairment declines.', 'Credit spreads and liquidity premiums contract.', 'Financials and risk assets receive support if the remedy is credible and sufficient.'),
        transmissions=(
            tx('credit', TransmissionDirection.POSITIVE, 0.65, 'Lower default and liquidity risk support credit returns.', 'short_to_medium_term'),
            tx('financials', TransmissionDirection.POSITIVE, 0.55, 'Reduced funding and counterparty stress supports financial institutions.', 'short_to_medium_term'),
            tx('broad_equities', TransmissionDirection.POSITIVE, 0.35, 'Lower contagion risk supports risk appetite.', 'short_to_medium_term'),
            tx('volatility', TransmissionDirection.NEGATIVE, 0.45, 'Reduced uncertainty lowers hedging demand.', 'short_to_medium_term'),
        ),
        alternatives=('The remedy may transfer losses rather than eliminate them.', 'Dilution, guarantees, or restrictive terms may limit upside.'),
    ),
    rule(
        'operational-cyber-disruption',
        EventMarketDomain.OPERATIONAL_CYBER,
        EventMarketState.OPERATIONAL_DISRUPTION,
        ('cyberattack', 'ransomware', 'data breach', 'systems outage', 'service outage', 'factory shutdown', 'production halt', 'network disruption', 'cloud outage', 'payment outage', 'operations suspended', 'critical vulnerability exploited'),
        context=(),
        excluded=(),
        channels=('cyber', 'operational', 'earnings', 'counterparty'),
        priority=0.75,
        chain=('Operations, data, customer access, or critical infrastructure are impaired.', 'Lost revenue, remediation costs, legal exposure, and uncertainty rise.', 'Effects concentrate in exposed issuers and dependencies unless the disruption is systemic.'),
        transmissions=(
            tx('affected_issuer', TransmissionDirection.NEGATIVE, 0.75, 'Operational impairment and remediation costs reduce expected cash flow.', 'short_to_medium_term'),
            tx('affected_customers', TransmissionDirection.NEGATIVE, 0.4, 'Customers may face downtime, switching costs, or lost activity.', 'short_to_medium_term'),
            tx('cybersecurity_vendors', TransmissionDirection.POSITIVE, 0.3, 'Demand for remediation and security controls may increase.', 'short_to_medium_term'),
            tx('volatility', TransmissionDirection.POSITIVE, 0.35, 'Uncertain scope and duration increase risk premiums.', 'short_to_medium_term'),
        ),
        alternatives=('The incident may be contained with limited financial impact.', 'Insurance, redundancy, or rapid restoration may reduce losses.'),
    ),
    rule(
        'disaster-recovery',
        EventMarketDomain.WEATHER_DISASTER,
        EventMarketState.DISASTER_RECOVERY,
        ('containment improves', 'fire contained', 'flood waters recede', 'power restored', 'reconstruction begins', 'storm passes', 'ports reopen', 'evacuation lifted'),
        context=(),
        excluded=(),
        channels=('climate_weather', 'operational', 'supply'),
        priority=0.75,
        chain=('Immediate physical disruption declines.', 'Production, transport, and local activity begin to normalize.', 'Reconstruction demand rises while residual losses remain to be measured.'),
        transmissions=(
            tx('affected_region', TransmissionDirection.POSITIVE, 0.45, 'Normalization reduces disruption risk.', 'short_to_medium_term'),
            tx('reconstruction', TransmissionDirection.POSITIVE, 0.5, 'Repair and rebuilding demand increases.', 'short_to_medium_term'),
            tx('supply_chain', TransmissionDirection.POSITIVE, 0.35, 'Restored transport and production reduce delays.', 'short_to_medium_term'),
        ),
        alternatives=('Residual damage, insurance disputes, or capacity loss may persist.', 'Reconstruction may be delayed by labor, materials, or financing constraints.'),
    ),
    rule(
        'political-uncertainty',
        EventMarketDomain.POLITICAL_ELECTION,
        EventMarketState.POLITICAL_UNCERTAINTY,
        ('contested election', 'political crisis', 'coalition collapse', 'government falls', 'impeachment', 'constitutional crisis', 'election violence', 'policy uncertainty rises'),
        context=(),
        excluded=(),
        channels=('policy', 'geopolitical', 'currency', 'volatility'),
        priority=0.75,
        chain=('The future policy, institutional, or fiscal path becomes less certain.', 'Country and currency risk premiums rise.', 'Locally exposed assets face volatility until authority and policy direction clarify.'),
        transmissions=(
            tx('affected_region', TransmissionDirection.NEGATIVE, 0.6, 'Higher institutional uncertainty raises required returns.', 'short_to_medium_term'),
            tx('local_currency', TransmissionDirection.NEGATIVE, 0.45, 'Capital outflow and policy uncertainty can pressure the currency.', 'short_to_medium_term'),
            tx('volatility', TransmissionDirection.POSITIVE, 0.5, 'Uncertain policy outcomes increase risk premiums.', 'short_to_medium_term'),
        ),
        alternatives=('Institutions may contain the dispute without policy disruption.', 'Markets may prefer the likely policy outcome despite procedural uncertainty.'),
    ),
    rule(
        'market-liquidity-relief',
        EventMarketDomain.MARKET_LIQUIDITY,
        EventMarketState.LIQUIDITY_RELIEF,
        ('liquidity facility', 'funding markets normalize', 'spreads narrow', 'market depth improves', 'trading resumes', 'redemptions stabilize', 'margin pressure eases', 'liquidity restored'),
        context=(),
        excluded=(),
        channels=('liquidity', 'credit', 'volatility'),
        priority=0.75,
        chain=('Market depth or funding availability improves.', 'Forced-selling and liquidity premiums decline.', 'Credit and less-liquid risk assets receive support if the improvement persists.'),
        transmissions=(
            tx('liquidity', TransmissionDirection.POSITIVE, 0.75, 'Market depth and funding access improve.', 'short_to_medium_term'),
            tx('credit', TransmissionDirection.POSITIVE, 0.55, 'Liquidity premiums and refinancing risk decline.', 'short_to_medium_term'),
            tx('small_caps', TransmissionDirection.POSITIVE, 0.4, 'Less-liquid assets benefit from improved market function.', 'short_to_medium_term'),
            tx('volatility', TransmissionDirection.NEGATIVE, 0.5, 'Improved depth reduces flow-driven amplification.', 'short_to_medium_term'),
        ),
        alternatives=('The improvement may depend on temporary official support.', 'Underlying solvency problems may remain despite better liquidity.'),
    ),
)

__all__=["RULES_PART_1"]
