"""Part 2 of the versioned general event-market rule catalog."""
from intelligence.event_market_rule_builders import (
    EventMarketDomain, EventMarketState, TransmissionDirection, rule, tx,
)

RULES_PART_2 = (
    rule(
        'energy-geopolitical-escalation',
        EventMarketDomain.COMMODITY_SUPPLY,
        EventMarketState.GEOPOLITICAL_ESCALATION,
        ('military strike', 'airstrike', 'missile strike', 'blockade', 'retaliation', 'war expands', 'armed conflict', 'shipping attacked', 'strait closure'),
        context=('oil', 'crude', 'brent', 'wti', 'tanker', 'hormuz', 'persian gulf', 'energy shipping', 'petroleum'),
        excluded=(),
        channels=('geopolitical', 'supply', 'commodity'),
        priority=0.92,
        chain=('The probability of conflict-related energy disruption rises.', 'Expected tanker, pipeline, or export impairment increases.', 'The geopolitical supply-risk premium embedded in crude prices expands.', 'Higher fuel and input-cost expectations raise inflation and margin pressure.'),
        transmissions=(
            tx('crude_oil', TransmissionDirection.POSITIVE, 0.9, "Higher disruption probability increases crude oil's supply-risk premium.", 'immediate'),
            tx('energy_producers', TransmissionDirection.POSITIVE, 0.65, 'Higher expected crude realizations support producer cash flow.', 'short_to_medium_term'),
            tx('airlines', TransmissionDirection.NEGATIVE, 0.65, 'Higher jet-fuel expectations pressure margins.', 'short_to_medium_term'),
            tx('transportation', TransmissionDirection.NEGATIVE, 0.55, 'Higher fuel and freight-risk costs pressure margins.', 'short_to_medium_term'),
            tx('inflation_expectations', TransmissionDirection.POSITIVE, 0.45, 'Higher energy prices increase near-term inflation pressure.', 'short_to_medium_term'),
        ),
        alternatives=('Spare capacity, inventories, or rapid diplomacy may offset the disruption.', 'The conflict may remain contained without affecting physical flows.'),
    ),
    rule(
        'geopolitical-deescalation',
        EventMarketDomain.GEOPOLITICS,
        EventMarketState.GEOPOLITICAL_DEESCALATION,
        ('ceasefire', 'truce', 'peace deal', 'peace agreement', 'halt strikes', 'paused strikes', 'de-escalation', 'deescalation', 'talks progress', 'negotiations advance', 'hostages released', 'withdrawal agreement'),
        context=(),
        excluded=(),
        channels=('geopolitical', 'supply', 'volatility'),
        priority=0.75,
        chain=('The probability of conflict, sanctions, or physical disruption declines.', 'Geopolitical and tail-risk premiums contract.', 'Affected supply chains, currencies, and risk assets reprice toward normal conditions.'),
        transmissions=(
            tx('geopolitical_risk', TransmissionDirection.NEGATIVE, 0.85, 'Lower escalation probability reduces the geopolitical risk premium.', 'immediate'),
            tx('volatility', TransmissionDirection.NEGATIVE, 0.65, 'Reduced tail risk lowers demand for protection.', 'immediate'),
            tx('broad_equities', TransmissionDirection.POSITIVE, 0.5, 'Lower uncertainty and disruption risk support risk appetite.', 'short_to_medium_term'),
            tx('affected_region', TransmissionDirection.POSITIVE, 0.65, 'Regional risk premiums and expected disruption costs decline.', 'short_to_medium_term'),
        ),
        alternatives=('The agreement may fail or may not change physical conditions.', 'Markets may already have priced most of the de-escalation.'),
    ),
    rule(
        'commodity-supply-easing',
        EventMarketDomain.COMMODITY_SUPPLY,
        EventMarketState.SUPPLY_EASING,
        ('production restored', 'output restored', 'supply restored', 'pipeline reopens', 'port reopens', 'shipping resumes', 'inventory build', 'production increase', 'output increase', 'export resumes', 'capacity returns'),
        context=(),
        excluded=(),
        channels=('supply', 'commodity', 'operational'),
        priority=0.75,
        chain=('Available physical supply or transport capacity increases.', 'Scarcity and replacement costs decline.', 'Consumers may benefit while producer pricing power weakens.'),
        transmissions=(
            tx('affected_commodity', TransmissionDirection.NEGATIVE, 0.75, 'More available supply reduces scarcity value.', 'short_to_medium_term'),
            tx('commodity_producers', TransmissionDirection.NEGATIVE, 0.55, 'Lower expected prices reduce producer pricing support.', 'short_to_medium_term'),
            tx('commodity_consumers', TransmissionDirection.POSITIVE, 0.6, 'Lower input costs can improve margins.', 'short_to_medium_term'),
            tx('inflation_expectations', TransmissionDirection.NEGATIVE, 0.4, 'Lower input costs reduce near-term inflation pressure.', 'short_to_medium_term'),
            tx('supply_chain', TransmissionDirection.POSITIVE, 0.5, 'Restored capacity reduces delay and substitution costs.', 'short_to_medium_term'),
        ),
        alternatives=('Stronger demand may absorb the additional supply.', 'Restoration may be incomplete or operationally fragile.'),
    ),
    rule(
        'inflation-upside',
        EventMarketDomain.INFLATION,
        EventMarketState.INFLATION_ACCELERATION,
        ('cpi beats', 'inflation beats', 'inflation rises', 'inflation accelerates', 'prices accelerate', 'hot inflation', 'ppi beats', 'core inflation rises', 'wage inflation rises', 'inflation expectations rise'),
        context=(),
        excluded=(),
        channels=('inflation', 'discount_rate', 'policy'),
        priority=0.75,
        chain=('Expected inflation rises relative to prior expectations.', 'Expected policy rates, nominal yields, and required returns increase.', 'Long-duration assets and input-cost-sensitive margins face pressure.'),
        transmissions=(
            tx('inflation_expectations', TransmissionDirection.POSITIVE, 0.85, 'The release raises expected inflation.', 'short_to_medium_term'),
            tx('policy_rate_expectations', TransmissionDirection.POSITIVE, 0.7, 'Higher inflation can delay easing or increase tightening risk.', 'short_to_medium_term'),
            tx('bond_prices', TransmissionDirection.NEGATIVE, 0.7, 'Higher expected yields reduce bond prices.', 'short_to_medium_term'),
            tx('growth_equities', TransmissionDirection.NEGATIVE, 0.55, 'Higher discount rates reduce the present value of distant cash flows.', 'short_to_medium_term'),
            tx('us_dollar', TransmissionDirection.POSITIVE, 0.35, 'Higher relative rate expectations can support the currency.', 'short_to_medium_term'),
        ),
        alternatives=('The inflation increase may be narrow or temporary.', 'Weak growth may limit the central bank response.'),
    ),
    rule(
        'labor-weakening',
        EventMarketDomain.LABOR,
        EventMarketState.LABOR_WEAKENING,
        ('payrolls miss', 'jobs miss', 'unemployment rises', 'job losses', 'layoffs rise', 'job openings fall', 'labor market weakens', 'hiring slows'),
        context=(),
        excluded=(),
        channels=('growth', 'credit', 'policy'),
        priority=0.75,
        chain=('Labor income and household-demand expectations weaken.', 'Growth and credit concerns rise.', 'Expected policy rates may fall, supporting bonds while pressuring cyclicals.'),
        transmissions=(
            tx('cyclical_equities', TransmissionDirection.NEGATIVE, 0.55, 'Weaker employment threatens consumption and revenue.', 'short_to_medium_term'),
            tx('credit', TransmissionDirection.NEGATIVE, 0.45, 'Job losses can weaken borrower cash flows.', 'short_to_medium_term'),
            tx('policy_rate_expectations', TransmissionDirection.NEGATIVE, 0.5, 'A weaker labor market can accelerate easing expectations.', 'short_to_medium_term'),
            tx('bond_prices', TransmissionDirection.POSITIVE, 0.5, 'Lower expected rates support bond prices.', 'short_to_medium_term'),
        ),
        alternatives=('A modest cooling may be consistent with a soft landing.', 'Policy easing may offset the employment slowdown.'),
    ),
    rule(
        'fiscal-expansion',
        EventMarketDomain.FISCAL_POLICY,
        EventMarketState.FISCAL_EXPANSION,
        ('stimulus package', 'spending package', 'tax cuts', 'infrastructure bill', 'fiscal expansion', 'government spending increase', 'deficit spending'),
        context=(),
        excluded=(),
        channels=('growth', 'inflation', 'policy'),
        priority=0.75,
        chain=('Expected public spending or disposable income rises.', 'Growth and sector demand improve, while deficits and inflation pressure may increase.', 'Beneficiary sectors and bond yields reprice to the package composition and financing need.'),
        transmissions=(
            tx('cyclical_equities', TransmissionDirection.POSITIVE, 0.55, 'Higher fiscal demand supports activity and revenue.', 'short_to_medium_term'),
            tx('infrastructure', TransmissionDirection.POSITIVE, 0.65, 'Direct public spending supports project demand.', 'short_to_medium_term'),
            tx('inflation_expectations', TransmissionDirection.POSITIVE, 0.35, 'Additional demand can increase inflation pressure.', 'short_to_medium_term'),
            tx('bond_prices', TransmissionDirection.NEGATIVE, 0.4, 'Higher deficits and inflation expectations can raise yields.', 'short_to_medium_term'),
        ),
        alternatives=('Implementation may be delayed or smaller than announced.', 'Tax increases, crowding out, or tighter policy may offset the stimulus.'),
    ),
    rule(
        'trade-restriction',
        EventMarketDomain.TRADE_SANCTIONS,
        EventMarketState.TRADE_RESTRICTION,
        ('tariff', 'export control', 'trade restriction', 'sanctions imposed', 'import ban', 'embargo', 'blacklist', 'trade war', 'export ban'),
        context=(),
        excluded=(),
        channels=('regulation', 'geopolitical', 'supply', 'currency'),
        priority=0.75,
        chain=('Cross-border access to goods, technology, capital, or payments is restricted.', 'Affected supply chains face higher costs, delays, or lost demand.', 'Domestic substitutes may benefit while exposed importers and exporters face pressure.'),
        transmissions=(
            tx('affected_exporters', TransmissionDirection.NEGATIVE, 0.65, 'Restricted market access reduces expected sales.', 'short_to_medium_term'),
            tx('affected_importers', TransmissionDirection.NEGATIVE, 0.55, 'Tariffs and restrictions raise input costs.', 'short_to_medium_term'),
            tx('domestic_substitutes', TransmissionDirection.POSITIVE, 0.45, 'Protected local suppliers may gain pricing power.', 'short_to_medium_term'),
            tx('inflation_expectations', TransmissionDirection.POSITIVE, 0.35, 'Trade barriers can raise landed costs.', 'short_to_medium_term'),
            tx('supply_chain', TransmissionDirection.NEGATIVE, 0.55, 'Restrictions increase sourcing and compliance friction.', 'short_to_medium_term'),
        ),
        alternatives=('Exemptions, rerouting, or inventory may reduce the impact.', 'Retaliation may broaden the effects beyond initially named sectors.'),
    ),
    rule(
        'credit-stress',
        EventMarketDomain.CREDIT_FINANCIAL_STABILITY,
        EventMarketState.CREDIT_STRESS,
        ('default', 'bank failure', 'bank run', 'deposit outflow', 'liquidity crisis', 'credit event', 'downgrade', 'missed payment', 'restructuring', 'insolvency', 'margin call', 'counterparty failure', 'rescue talks'),
        context=(),
        excluded=(),
        channels=('credit', 'liquidity', 'counterparty', 'volatility'),
        priority=0.75,
        chain=('The probability of loss, funding stress, or counterparty impairment rises.', 'Credit spreads and liquidity premiums increase.', 'Financials and risk assets face contagion pressure while safe assets may benefit.'),
        transmissions=(
            tx('credit', TransmissionDirection.NEGATIVE, 0.8, 'Higher default and liquidity risk pressure credit returns.', 'short_to_medium_term'),
            tx('financials', TransmissionDirection.NEGATIVE, 0.7, 'Funding and counterparty concerns pressure financial institutions.', 'short_to_medium_term'),
            tx('broad_equities', TransmissionDirection.NEGATIVE, 0.55, 'Contagion and tighter financing pressure risk assets.', 'short_to_medium_term'),
            tx('volatility', TransmissionDirection.POSITIVE, 0.7, 'Uncertainty and hedging demand increase.', 'short_to_medium_term'),
            tx('treasuries', TransmissionDirection.POSITIVE, 0.45, 'Safe-haven demand and lower rate expectations can support Treasuries.', 'short_to_medium_term'),
        ),
        alternatives=('The event may be isolated and fully contained.', 'Official liquidity support or a credible acquisition may stop contagion.'),
    ),
    rule(
        'regulatory-relief',
        EventMarketDomain.REGULATION_LEGAL,
        EventMarketState.REGULATORY_RELIEF,
        ('rule withdrawn', 'regulation eased', 'approval granted', 'permit approved', 'license renewed', 'lawsuit dismissed', 'fine reduced', 'ban lifted', 'capital requirement reduced', 'antitrust clearance'),
        context=(),
        excluded=(),
        channels=('regulation', 'operational', 'earnings'),
        priority=0.75,
        chain=('Compliance costs, operating restrictions, or legal-loss probability decline.', 'Affected issuer or sector cash-flow expectations improve.', 'The benefit depends on implementation timing and competitive response.'),
        transmissions=(
            tx('affected_issuer', TransmissionDirection.POSITIVE, 0.7, 'Lower costs or restrictions improve issuer value.', 'short_to_medium_term'),
            tx('affected_sector', TransmissionDirection.POSITIVE, 0.45, 'The action can improve sector profitability or flexibility.', 'short_to_medium_term'),
        ),
        alternatives=('The relief may be narrow, temporary, or already priced.', 'Competitors may respond by increasing capacity or price competition.'),
    ),
    rule(
        'weather-disaster',
        EventMarketDomain.WEATHER_DISASTER,
        EventMarketState.DISASTER_ESCALATION,
        ('hurricane', 'earthquake', 'wildfire', 'flood', 'tornado', 'drought', 'major storm', 'disaster declaration', 'extreme heat', 'freeze', 'tsunami', 'volcanic eruption'),
        context=(),
        excluded=(),
        channels=('climate_weather', 'supply', 'operational', 'commodity'),
        priority=0.75,
        chain=('Physical assets, transport, production, or insured property are exposed.', 'Capacity loss, reconstruction costs, and supply disruption rise.', 'Market effects depend on location, duration, economic concentration, and insurance coverage.'),
        transmissions=(
            tx('affected_region', TransmissionDirection.NEGATIVE, 0.65, 'Local production and asset values face disruption.', 'short_to_medium_term'),
            tx('insurers', TransmissionDirection.NEGATIVE, 0.45, 'Expected claims and capital usage rise.', 'short_to_medium_term'),
            tx('reconstruction', TransmissionDirection.POSITIVE, 0.35, 'Rebuilding demand can increase after the immediate shock.', 'short_to_medium_term'),
            tx('affected_commodity', TransmissionDirection.POSITIVE, 0.35, 'Production or transport losses can tighten supply.', 'short_to_medium_term'),
            tx('supply_chain', TransmissionDirection.NEGATIVE, 0.45, 'Transport and production interruptions increase delay and cost.', 'short_to_medium_term'),
        ),
        alternatives=('The hazard may miss economically important assets.', 'Redundancy, inventories, and insurance may limit financial losses.'),
    ),
    rule(
        'public-health-improvement',
        EventMarketDomain.PUBLIC_HEALTH,
        EventMarketState.HEALTH_IMPROVEMENT,
        ('cases fall', 'outbreak contained', 'emergency ended', 'restrictions lifted', 'vaccine effective', 'treatment approved', 'hospitalizations fall'),
        context=(),
        excluded=(),
        channels=('growth', 'operational', 'demand'),
        priority=0.75,
        chain=('Health risk and behavioral restrictions decline.', 'Travel, labor supply, and consumer activity normalize.', 'Previously impaired sectors receive support while emergency-demand beneficiaries may normalize.'),
        transmissions=(
            tx('travel_leisure', TransmissionDirection.POSITIVE, 0.55, 'Travel and gathering activity can recover.', 'short_to_medium_term'),
            tx('broad_equities', TransmissionDirection.POSITIVE, 0.35, 'Lower growth and operational uncertainty supports risk assets.', 'short_to_medium_term'),
            tx('volatility', TransmissionDirection.NEGATIVE, 0.3, 'Reduced uncertainty lowers risk premiums.', 'short_to_medium_term'),
        ),
        alternatives=('New variants or waning protection may reverse the improvement.', 'Behavior and supply constraints may normalize slowly.'),
    ),
    rule(
        'market-liquidity-stress',
        EventMarketDomain.MARKET_LIQUIDITY,
        EventMarketState.LIQUIDITY_STRESS,
        ('market dislocation', 'liquidity freeze', 'funding stress', 'repo spike', 'bid ask spreads widen', 'trading halt', 'forced selling', 'redemptions surge', 'margin calls', 'market depth collapses'),
        context=(),
        excluded=(),
        channels=('liquidity', 'credit', 'volatility', 'positioning'),
        priority=0.75,
        chain=('Market depth or funding availability deteriorates.', 'Forced selling and liquidity premiums increase.', 'Leveraged, lower-quality, and crowded assets face disproportionate pressure.'),
        transmissions=(
            tx('liquidity', TransmissionDirection.NEGATIVE, 0.85, 'Market depth and funding access deteriorate.', 'short_to_medium_term'),
            tx('credit', TransmissionDirection.NEGATIVE, 0.65, 'Liquidity premiums and refinancing risk rise.', 'short_to_medium_term'),
            tx('small_caps', TransmissionDirection.NEGATIVE, 0.5, 'Less liquid assets face greater price pressure.', 'short_to_medium_term'),
            tx('volatility', TransmissionDirection.POSITIVE, 0.7, 'Forced flows and poor depth amplify moves.', 'short_to_medium_term'),
            tx('treasuries', TransmissionDirection.POSITIVE, 0.3, 'Safe-haven demand may rise unless Treasury liquidity is itself impaired.', 'short_to_medium_term'),
        ),
        alternatives=('The dislocation may be technical and short-lived.', 'Official liquidity facilities may restore market function quickly.'),
    ),
    rule(
        'technology-breakthrough',
        EventMarketDomain.TECHNOLOGY_INNOVATION,
        EventMarketState.TECHNOLOGY_BREAKTHROUGH,
        ('breakthrough', 'major discovery', 'clinical breakthrough', 'commercial launch', 'technology milestone', 'record efficiency', 'successful trial', 'patent granted', 'new platform released', 'production breakthrough'),
        context=(),
        excluded=(),
        channels=('earnings', 'operational', 'innovation', 'sentiment'),
        priority=0.75,
        chain=('A new capability may improve revenue, cost, productivity, or competitive position.', 'Affected issuer and ecosystem cash-flow assumptions change.', 'Incumbents or substitutes face disruption only when commercialization is credible.'),
        transmissions=(
            tx('affected_issuer', TransmissionDirection.POSITIVE, 0.65, 'The capability may improve issuer growth or margins.', 'short_to_medium_term'),
            tx('technology_suppliers', TransmissionDirection.POSITIVE, 0.35, 'Enabling suppliers may gain demand.', 'short_to_medium_term'),
            tx('disrupted_incumbents', TransmissionDirection.NEGATIVE, 0.35, 'Substitution risk can pressure incumbent economics.', 'short_to_medium_term'),
            tx('affected_sector', TransmissionDirection.MIXED, 0.35, 'The breakthrough creates winners and losers within the sector.', 'short_to_medium_term'),
        ),
        alternatives=('Commercialization, scaling, regulation, or economics may fail.', 'The announcement may be incremental or already anticipated.'),
    ),
)

__all__=["RULES_PART_2"]
